const theme = {
  colors: {
    background: '#fff',
    primary: '#d22e2e',
    buttonText: '#fff',
    headerBackground: '#fbfbfb',
    headerContact: '#999',
    headerContactTitle: '#666',
    headerLinks: '#404040',
    headerBorder: '#e5e5e5',
    menuItem: '#404040',
    menuSubItem: '#666',
    menuSubItemBorder: '#e5e5e5',
    searchBackground: '#fff',
    searchText: '#777',
    cartBackground: '#fff',
    cartProductName: '#373636',
    cartProductDescription: '#a6a6a6',
    cartProductDelete: '#000',
    cartProductBorder: '#eaeaea',
    cartSubtotal: '#777',
    cartCheckButton: '#222',
    sectionTitle: '#373636',
    sectionTitleBackground: '#f6f6f6',
    breadcrumb: '#b2b2b2',
    widgetTitle: '#373636',
    categoriesItem: '#666666',
    recentItem: '#1b1a1a',
    recentItemBorder: '#e9e9e9',
    price: '#666666',
    brandsItem: '#666666',
    brandsItemCheckboxBorder: '#e5e5e5',
    brandsItemCheckboxBackground: '#fff',
    tagItem: '#a6a6a6',
    tagBorder: '#e5e5e5',
    shopOptionsTitle: '#000',
    shopOptionsBorder: '#e5e5e5',
    shopOptionsSelect: '#999',
    shopOptionsSelectBorder: '#e5e5e5',
    shopOptionsGrid: '#777',
    shopOptionsGridBorder: '#e5e5e5',
    productBrand: '#666',
    productName: '#373636',
    productHover: 'rgba(0, 0, 0, 0.8)',
    pagination: '#666',
    paginationBackground: '#f6f6f6',
    paginationActive: '#fff',
    footerBackground: '#191919',
    footerInfoTitle: '#fff',
    footerInfoDescription: '#999',
    footerInfoIcon: '#000',
    footerInfoBorder: '#232323',
    footerInfoPanelBorder: 'rgba(229, 229, 229, 0.1)',
    footerWidgetTitle: '#fff',
    footerWidgetDescription: '#999',
    footerWidgetLink: '#acacac',
    footerWidgetLinkBorder: '#242424',
    footerWidgetSocials: '#acacac',
    footerWidgetSocialsHover: '#fff',
    footerWidgetSocialsBackground: '#141414',
    footerCopyrightBackground: '#141414',
    footerCopyright: '#666',
    footerCopyrightLink: '#acacac',
    footerCompanies: '#666',
    footerCompaniesIconHover: '#fff',
    discount: '#6c6c6c',
    facebook: '#3B5998',
    googlePlus: '#DD4B39',
    twitter: '#00ACEE',
    pinterest: '#C8232C',
    vimeo: '#86C9EF',
    wifi: '#EE802F',
    dribbble: '#EA4C89'
  }
}

export default theme
